### ISSUE TITLE
Can't install new extension with Invalid credentials (HTTP 403) Error

### ISSUE THREAD

**Issue by MIKU-N** [flarum-com/flarum-org#17]
I just want install a new extension,but the composer always tell me Invalid credentials (HTTP 403) Error:
![image](https://github.com/flarum-com/flarum-org/assets/61493780/e4fa712e-1285-4dd1-8171-54e5dd24b7cf)
I see the new extension dashboard,I get a new token in https://flarum.org/dashboard/subscriptions,and I do this:

- set Composer token 
```
sudo -u www composer config --global bearer.flarum.org  mytoken
```
- set Composer Repository
```
sudo -u www composer config repositories.flarum composer https://flarum.org/composer
```
then i runing this commad 
```
sudo -u www composer update
```
and the error was happened

I see somebody has same error,but I can't solve it in the same way
- https://discuss.flarum.org/d/34621-invalid-credentials-http-403/4
- https://discuss.flarum.org/d/32812-the-future-of-flarum-in-2023-balancing-open-source-and-success/61

**Comment by luceos** [comment]
www might not have a home directory, setting the token might actually fail. As a solution try setting the token not globally but only in the directory. Rerun the composer config auth command without the --global flag and see if that helps.

**Comment by MIKU-N** [comment]
> www might not have a home directory, setting the token might actually fail. As a solution try setting the token not globally but only in the directory. Rerun the composer config auth command without the --global flag and see if that helps.

Thanks for you reply,but I confirmed that www has a user directory,and has `.config/composer/auth.json` file.
And I just tried removing `--global` flag ,it doesn't work...
![image](https://github.com/flarum-com/flarum-org/assets/61493780/e8ad2099-4f91-4288-a7b7-8eba1e74d5a1)

**Comment by luceos** [comment]
Then I recommend retrieving a new token and storing that anew. Somehow it is probably not using the right one. If that doesn't work you can try running `composer update` with `-vvv` to debug what it does while trying to hit the flarum.org endpoint.

**Comment by MIKU-N** [comment]
> Then I recommend retrieving a new token and storing that anew. Somehow it is probably not using the right one. If that doesn't work you can try running `composer update` with `-vvv` to debug what it does while trying to hit the flarum.org endpoint.

```
# sudo -u www composer update -vvv
Running 2.7.6 (2024-05-04 23:03:15) with PHP 8.2.19 on Linux / 6.1.0-20-amd64
Reading ./composer.json (/www/wwwroot/**website**/composer.json)
Loading config file /home/www/.config/composer/config.json
Loading config file /home/www/.config/composer/auth.json
Loading config file ./composer.json (/www/wwwroot/website/composer.json)
Loading config file /www/wwwroot/website/auth.json
Reading /www/wwwroot/website/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/www/wwwroot/website): 'git' 'branch' '-a' '--no-color' '--no-abbrev' '-v'
Executing command (/www/wwwroot/website): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/www/wwwroot/website): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/www/wwwroot/website): hg branch
Executing command (/www/wwwroot/website): fossil branch list
Executing command (/www/wwwroot/website): fossil tag list
Executing command (/www/wwwroot/website): svn info --xml
Reading /home/www/.config/composer/composer.json
Loading config file /home/www/.config/composer/config.json
Loading config file /home/www/.config/composer/auth.json
Loading config file /home/www/.config/composer/composer.json (/home/www/.config/composer/composer.json)
Loading config file /home/www/.config/composer/auth.json
Reading /home/www/.config/composer/auth.json
Reading ./composer.lock (/www/wwwroot/website/composer.lock)
Reading /www/wwwroot/website/vendor/composer/installed.json
Loading composer repositories with package information
Downloading https://flarum.org/composer/packages.json
[403] https://flarum.org/composer/packages.json
[403] https://flarum.org/composer/packages.json

In AuthHelper.php line 216:
                                                                                             
  [Composer\Downloader\TransportException (100)]                                             
  Invalid credentials (HTTP 403) for 'https://flarum.org/composer/packages.json', aborting.  
                                                                                             

Exception trace:
  at phar:///usr/bin/composer/src/Composer/Util/AuthHelper.php:216
 Composer\Util\AuthHelper->promptAuthIfNeeded() at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:547
 Composer\Util\Http\CurlDownloader->isAuthenticatedRetryNeeded() at phar:///usr/bin/composer/src/Composer/Util/Http/CurlDownloader.php:413
 Composer\Util\Http\CurlDownloader->tick() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:392
 Composer\Util\HttpDownloader->countActiveJobs() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:363
 Composer\Util\HttpDownloader->wait() at phar:///usr/bin/composer/src/Composer/Util/HttpDownloader.php:114
 Composer\Util\HttpDownloader->get() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:1486
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:1195
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:823
 Composer\Repository\ComposerRepository->hasProviders() at phar:///usr/bin/composer/src/Composer/Repository/ComposerRepository.php:484
 Composer\Repository\ComposerRepository->loadPackages() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:425
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:275
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/bin/composer/src/Composer/Repository/RepositorySet.php:331
 Composer\Repository\RepositorySet->createPool() at phar:///usr/bin/composer/src/Composer/Installer.php:501
 Composer\Installer->doUpdate() at phar:///usr/bin/composer/src/Composer/Installer.php:298
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:251
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:394
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:148
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:93
 require() at /usr/bin/composer:29

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [-i|--interactive] [--root-reqs] [--] [<packages>...]
```
new token and storing that anew...Also don't work...

**Comment by luceos** [comment]
If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.

**Comment by MIKU-N** [comment]
> If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.

I konw why I get 403 error now..
My server ip adress was block by cloudflare JS challenge....So fuck it????
I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS  challenge...
I can't change the server IP because of this problem, how can I solve this?

**Comment by luceos** [comment]
> > If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.
> 
> I konw why I get 403 error now.. My server ip adress was block by cloudflare JS challenge....So fuck it???? I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS challenge... I can't change the server IP because of this problem, how can I solve this?

Send me your server ip in discord DM or by email. My email is in my discuss BIO. I will see if I can unblock it in CF for you.

**Comment by MIKU-N** [comment]
> > > If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.
> > 
> > 
> > I konw why I get 403 error now.. My server ip adress was block by cloudflare JS challenge....So fuck it???? I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS challenge... I can't change the server IP because of this problem, how can I solve this?
> 
> Send me your server ip in discord DM or by email. My email is in my discuss BIO. I will see if I can unblock it in CF for you.

I send my server ip in email to your  flarum.com adress. plz confirm

**Comment by luceos** [comment]
> > > > If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.
> > > 
> > > 
> > > I konw why I get 403 error now.. My server ip adress was block by cloudflare JS challenge....So fuck it???? I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS challenge... I can't change the server IP because of this problem, how can I solve this?
> > 
> > 
> > Send me your server ip in discord DM or by email. My email is in my discuss BIO. I will see if I can unblock it in CF for you.
> 
> I send my server ip in email to your flarum.com adress. plz confirm

IP added to CF, see if this resolves it.

**Comment by MIKU-N** [comment]
> > > > > If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.
> > > > 
> > > > 
> > > > I konw why I get 403 error now.. My server ip adress was block by cloudflare JS challenge....So fuck it???? I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS challenge... I can't change the server IP because of this problem, how can I solve this?
> > > 
> > > 
> > > Send me your server ip in discord DM or by email. My email is in my discuss BIO. I will see if I can unblock it in CF for you.
> > 
> > 
> > I send my server ip in email to your flarum.com adress. plz confirm
> 
> IP added to CF, see if this resolves it.

Also Failed...This 403 is come from CF
![image](https://github.com/flarum-com/flarum-org/assets/61493780/60f521b6-d822-4c87-a5a0-65bbab9d8859)

**Comment by MIKU-N** [comment]
> > > > > If you delete both the `auth.json` in the web root and the `.config/composer/auth.json` in the home directory it should throw a different error stating it cannot find a package which is currently installed. Please try that. Then after that follow all the steps from https://flarum.org/dashboard/subscriptions again.
> > > > 
> > > > 
> > > > I konw why I get 403 error now.. My server ip adress was block by cloudflare JS challenge....So fuck it???? I use Postman to test flarum.org endpoint in my desktop,it was working but when i used curl in my server,it result JS challenge... I can't change the server IP because of this problem, how can I solve this?
> > > 
> > > 
> > > Send me your server ip in discord DM or by email. My email is in my discuss BIO. I will see if I can unblock it in CF for you.
> > 
> > 
> > I send my server ip in email to your flarum.com adress. plz confirm
> 
> IP added to CF, see if this resolves it.

Look like CF block was over,I successed update now,thanks your help
