### ISSUE TITLE
Email confirmation doesn't work, invalid signature

### ISSUE THREAD

**Issue by luceos** [flarum-com/flarum-org#2]

**Comment by luceos** [comment]
Just resolved by forcing CF to send the Forwarded Port header as 443 instead of 80. Seems Symfony Request relies on this header when determining if the request is secured for proxies.

**Comment by hongaar** [comment]
Follow-up from https://discuss.flarum.org/d/32812-the-future-of-flarum-in-2023-balancing-open-source-and-success/76

Not sure if this is a caching issue, but I still get the same `403 INVALID SIGNATURE.` error. Some more details which may help you debug this issue:

1. Click the "Resend verification email" button on https://flarum.org/email/verify
2. See a page which says "A fresh verification link has been sent to your email address."
3. Receive email with "Verify Email Address" button which links to https://flarum.org/email/verify/{numeric}/{hash}?expires={timestamp}&signature={hash}
4. Click that button
5. Receive the error

<details><summary>Response headers</summary>

```
Alt-Svc:
h3=":443"; ma=86400
Cache-Control:
no-cache, private
Cf-Cache-Status:
DYNAMIC
Cf-Ray:
{truncated}
Content-Encoding:
br
Content-Type:
text/html; charset=UTF-8
Date:
Wed, 29 May 2024 07:40:57 GMT
Nel:
{"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Priority:
u=0,i
Ratelimit-Limit:
60
Ratelimit-Remaining:
59
Ratelimit-Reset:
1
Report-To:
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s={truncated}"}],"group":"cf-nel","max_age":604800}
Server:
cloudflare
Set-Cookie:
XSRF-TOKEN={truncated}; expires=Wed, 29 May 2024 09:40:57 GMT; Max-Age=7200; path=/; domain=flarum.org; samesite=lax
Set-Cookie:
laravel_token={truncated}; expires=Wed, 29 May 2024 09:40:57 GMT; Max-Age=7200; path=/; domain=flarum.org; httponly; samesite=lax
Set-Cookie:
laravel_session={truncated}; expires=Wed, 29 May 2024 09:40:57 GMT; Max-Age=7200; path=/; domain=flarum.org; httponly; samesite=lax

Via:
kong/3.5.0
X-Kong-Proxy-Latency:
1
X-Kong-Request-Id:
{truncated}
X-Kong-Upstream-Latency:
71
X-Ratelimit-Limit:
6
X-Ratelimit-Limit-Second:
60
X-Ratelimit-Remaining:
4
X-Ratelimit-Remaining-Second:
59
```

</details>

If you need additional details, you can reach me at [joram@vandenboezem.nl](mailto:joram@vandenboezem.nl)

**Comment by luceos** [comment]
After diving into this for more hours than I hoped, looking into both the Laravel and Symfony request handling. I discovered that the Laravel throttler was replacing the proxy settings to check the IP against a whitelist. A fix is being deployed.
