### ISSUE TITLE
Extension Sync API Returns 415

### ISSUE THREAD

**Issue by DavideIadeluca** [flarum-com/flarum-org#20]
The API for syncing Extensions with Flarum.org seems to have broken in the last couple of days. When trying to request the endpoint `https://flarum.org/api/premium-extensions/$VENDOR/$PACKAGE/sync` the following is returned:

```
{
   "errors":[
      {
         "status":"415",
         "title":"Unsupported Media Type",
         "detail":""
      }
   ],
   "jsonapi":{
      "version":"1.1"
   }
}

```

The same implementation was working previously on Extiverse.com and was fixed for Flarum.org.

**Comment by luceos** [comment]
Is this still an issue @DavideIadeluca ; sorry I missed this one.

**Comment by DavideIadeluca** [comment]
No worries @luceos. Yes, it still appears to be an issue:
<img width="917" alt="Screenshot 2024-07-25 at 07 00 04" src="https://github.com/user-attachments/assets/0f3d5a75-5ed2-48b2-bfde-1c9b5bec5054">

https://flarum.org/premium-developers/premium-extensions/bce89b49-cfd9-46d1-a64d-aa9738667a10 would be the extension I just tried to sync for demo purposes with the tag 0.0.37

**Comment by luceos** [comment]
Okay, edit the url:


**PATCH** `https://flarum.org/api/premium-extensions/$VENDOR/$PACKAGE`


It is possible that the extiverse token is no longer functioning as well, this is due to the domain change.

`2024.7.55`
